### ISSUE TITLE
Is there a way to install Convert::ASN1 offline

### ISSUE THREAD

**Issue by Asalle** [gbarr/perl-Convert-ASN1#30]
I run Cygwin and while installing OpenLDAP client called led I ran into an error
Net::LDAP ....................** FAILED **
Can't locate Convert/ASN1.pm in @INC
The Net::LDAP module is required for led
I don't want to start network things on Cygwin, and I haven't found any offline installation notes.

**Comment by Corion** [comment]
This is not really an issue with Convert::ASN1. How are you trying to install the Net::LDAP module?

The recommended way is to use the "cpan" tool that comes with Perl. It will download all prerequisite modules and install them. If you are doing a manual installation of Net::LDAP, you will need to find all its prerequisite modules, download them and install them and their prerequisites as well.
