### ISSUE TITLE
"Redundant argument in printf" warning on Debug.pm line 98 with perl 5.32

### ISSUE THREAD

**Issue by chrisridd** [gbarr/perl-Convert-ASN1#44]
I also see this in perl5.28 and perl5.30, but I've not been following perl5 development closely enough to know when this changed or broke.

With `-w` and `use warnings` in effect and Convert::ASN1 version 0.31, calling:

`Convert::ASN1::asn_dump(*STDOUT, $str);`

where $str is a bunch of raw BER, results in an annoying warning every time line 98 is hit:

`Redundant argument in printf at /opt/local/lib/perl5/vendor_perl/5.32/Convert/ASN1/Debug.pm line 98, <> line 1.
0000 1294: SEQUENCE {`

I see the same (unsurprisingly) using Net::LDAP's `debug(15)` mode.

**Comment by timlegge** [comment]
diff --git a/lib/Convert/ASN1/Debug.pm b/lib/Convert/ASN1/Debug.pm
index 905600b..099189a 100644
--- a/lib/Convert/ASN1/Debug.pm
+++ b/lib/Convert/ASN1/Debug.pm
@@ -95,7 +95,7 @@ sub asn_dump {
     my $label = $type{sprintf("%02X",$tag & ~0x20)}
                || $type{sprintf("%02X",$tag & 0xC0)}
                || "[UNIVERSAL %d]";
-    printf $label, $tnum;
+    printf "%s: %d\n", $label, $tnum;
 
     if ($tag & ASN_CONSTRUCTOR) {
       print " {\n";

**Comment by chrisridd** [comment]
You shouldn't include the "\n" in the format string, otherwise LGTM thanks @timlegge !

**Comment by timlegge** [comment]
Good point - I changed it to a print in a commit that I will be pushing
soon.
